# Generated by Django 5.0.7 on 2025-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('price_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
